INSERT INTO `departments` (`id`, `name`) VALUES
(1, 'Amazonas'),
(2, 'Ancash'),
(3, 'Apurimac'),
(4, 'Arequipa'),
(5, 'Ayacucho'),
(6, 'Cajamarca'),
(7, 'Cusco'),
(8, 'Huancavelica'),
(9, 'Huanuco'),
(10, 'Ica'),
(11, 'Junin'),
(12, 'La Libertad'),
(13, 'Lambayeque'),
(14, 'Lima'),
(15, 'Loreto'),
(16, 'Madre De Dios'),
(17, 'Moquegua'),
(18, 'Pasco'),
(19, 'Piura'),
(20, 'Puno'),
(21, 'San Martin'),
(22, 'Tacna'),
(23, 'Tumbes'),
(24, 'Prov. Const. Del Callao'),
(25, 'Ucayali');